; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = featheresp32

[env:featheresp32]
platform = espressif32
board = featheresp32
framework = arduino
monitor_speed = 115200

build_flags =
    -std=gnu++17

build_src_filter =
    +<*>
    -<sd_logger_test.cpp>

[env:unit_test]
platform = espressif32
board = featheresp32
framework = arduino
monitor_speed = 115200
test_framework = unity
test_build_src = yes

build_src_filter =
    +<PacketParser.cpp>
    +<LapManager.cpp>
    +<Button.cpp>
    -<main.cpp>
    -<sd_logger_test.cpp>

[env:sd_logger_test]
platform = espressif32
board = featheresp32
framework = arduino
monitor_speed = 115200

build_src_filter =
    +<sd_logger_test.cpp>
    +<SDLogger.cpp>
    +<SDLogger.h>
    +<PacketParser.cpp>
    +<PacketParser.h>
    -<main.cpp>